### ISSUE TITLE
output files generated without any data

### ISSUE THREAD

**Issue by AkhilJPatil** [jagodki/Batch-Interpolation#2]
Hello,

I am using the batch-interpolation plugin for rasterizing point data from weather data. I went as per the steps mentioned in the usage section of the readme.

Steps performed:
1. created a csv file with multiple point data values per per station
![image](https://user-images.githubusercontent.com/33284499/70706172-b8aa4600-1cd5-11ea-9843-74533f487ec1.png)

2. In QGIS, imported the csv as layer and opened it in the Batch-interpolation window
3. Chose all the attributes for creating the raster through interpolation
4. selected the method of interpolation (TIN) and pixel size(10). No option for contour selected.
5. Selected the output folder and clicked START
![image](https://user-images.githubusercontent.com/33284499/70706686-b72d4d80-1cd6-11ea-821e-12f93adbd8e2.png)

6. In the output folder location, 2 types of files (.asc and .prj) created per attribute
7. Data in the .asc files,
_NCOLS 0
NROWS 0
XLLCORNER 6.0244
YLLCORNER 47.3984
CELLSIZE 10
NODATA_VALUE -9999_

Please suggest,
Akhil

**Comment by jagodki** [comment]
Hi Akhil,

Sorry for my late response. I developed this plugin because QGIS 2 did not provide all functions from the menu bar in the processing toolbox, i.e. the raster interpolation. In QGIS 3 it is now available, i.e. you can easily create the same routine of this plugin using the model builder. The plugin is not necessary there. Is it possible for you to work with version 3 of QGIS (version 2 is depreciated)?

I do not have QGIS 2 on my machine anymore :( Do you still have the problem, if you just check one field? Maybe some of the fields have an unexpected content...

Sincerely,
Christoph

**Comment by AkhilJPatil** [comment]
Thanks for the response.

Yes I upgraded the QGIS to 3.4.1. 
There I found a 'TIN interpolation', under Processing Toolbox > Interpolation
It serves the purpose and I could generate raster from point data in batches.

Again, thanks for responding. I will close the issue.
Akhil
