### ISSUE TITLE
Update to 3.x Qgis

### ISSUE THREAD

**Issue by TiagoTostes** [jagodki/Batch-Interpolation#3]
Hello ,
I'm trying to use the batch interpolation plug-in for batch TIN-interpolation, but the plug-in does not work on Qgis 3.x or higher.
Can you update the plugin to the new version of Qgis?

Greetings,
Tiago.

**Comment by jagodki** [comment]
Hi Tiago,

an update of the plugin to QGIS 3 is not necessary, because the interpolation and batch processing are build-in features of QGIS 3. You can find the TIN-Interpolation via the processing toolbox and each processing algorithm offers the possibility to create a batch processing.

Greetings,
Christoph
